version: 0.2

cache:
  paths:
    - ".aws-sam/**/*"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - pip3 list
      - pip3 install aws-sam-cli -U
  build:
    commands:
      - sam build --cached
  post_build:
    commands:
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged_raw.yaml
      # Use timestamp to force update of ApiGatewayCreateDeploymentCustomResource
      - BUILD_TIMESTAMP=$(date '+%s')
      - envsubst '${BUILD_TIMESTAMP}' < packaged_raw.yaml > packaged.yaml
artifacts:
  files:
    - packaged.yaml