version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - pip3 install aws-sam-cli
  build:
    commands:
      # Force build of publication-commons to produce zip for Lambda Layer
      - ./gradlew :publication-commons:clean :publication-commons:build
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
