plugins {
    alias(libs.plugins.xjc)
}

dependencies {
    api(libs.xsd2java.jakarta)
    compileOnly(libs.jakarta.annotation.api)
    runtimeOnly(libs.jaxb.runtime4)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.junit.jupiter.api)
}

def schemaVersion = '4.6'
def metadataXsd = 'metadata.xsd'
def schemaDir = layout.buildDirectory.dir('tmp/schema')

tasks.register('fetchSchema') {
    def targetDir = schemaDir.get().asFile
    def version = schemaVersion
    def rootXsd = metadataXsd
    outputs.dir(targetDir)
    doLast {
        def downloadFile = { String path ->
            def target = new File(targetDir, path)
            def cached = target.exists()
            if (!cached) {
                target.parentFile.mkdirs()
                target.withOutputStream { output ->
                    new URI("https://schema.datacite.org/meta/kernel-${version}/${path}").toURL()
                    .withInputStream { input -> output << input }
                }
            }
            return new Tuple2<File, Boolean>(target, cached)
        }

        def (metadataFile, metadataCached) = downloadFile(rootXsd)
        def includedUris = new groovy.xml.XmlSlurper().parse(metadataFile).'**'.findAll {
            it.name() == 'include' || it.name() == 'import'
        }.collect {
            it.@'schemaLocation'.text()
        }

        def anyCached = metadataCached || includedUris.collect {
            downloadFile(it).v2
        }.any {
            it
        }
        if (anyCached) {
            logger.warn('WARN: Some XSD files were cached from a previous run, to avoid this, run ./gradlew clean')
        }
    }
}

jar {
    from "${layout.buildDirectory}/classes/java/main"
}

java {
    withSourcesJar()
}

tasks.named('sourcesJar') {
    dependsOn('xjc')
}

xjc {
    addCompilationDependencies = false
    markGenerated = true
    useJakarta = true
    xsdDir.set(schemaDir)
}

tasks.named('xjc') {
    dependsOn('fetchSchema')
}

tasks.named('compileJava') {
    dependsOn('xjc')
}
