AWSTemplateFormatVersion: '2010-09-09'
Description: Persisting NVA resources.

Parameters:
  ResourcesTableName:
    Description: Name to use for table persisting NVA resources.
    Type: String
    Default: nva_resources


Resources:
  NvaResourcesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ResourcesTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK0
          AttributeType: S
        - AttributeName: SK0
          AttributeType: S
        - AttributeName: PK1
          AttributeType: S
        - AttributeName: SK1
          AttributeType: S
        - AttributeName: PK2
          AttributeType: S
        - AttributeName: SK2
          AttributeType: S
        - AttributeName: PK3
          AttributeType: S
        - AttributeName: SK3
          AttributeType: S
      KeySchema:
        - AttributeName: PK0
          KeyType: HASH
        - AttributeName: SK0
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ByTypeCustomerStatus
          KeySchema:
            - AttributeName: PK1
              KeyType: HASH
            - AttributeName: SK1
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ByCustomerResource
          KeySchema:
            - AttributeName: PK2
              KeyType: HASH
            - AttributeName: SK2
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ResourcesByIdentifier
          KeySchema:
            - AttributeName: PK3
              KeyType: HASH
            - AttributeName: SK3
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true


Outputs:
  NvaResourcesTableName:
    Description: NVA resources table name.
    Value: !Ref NvaResourcesTable
    Export:
      Name: NvaResourcesTableName

  NvaResourcesTableArn:
    Description: NVA resources table ARN.
    Value: !GetAtt NvaResourcesTable.Arn
    Export:
      Name: NvaResourcesTableArn

  NvaResourcesTableStreamArn:
    Description: NVA resources table stream ARN.
    Value: !GetAtt NvaResourcesTable.StreamArn
    Export:
      Name: NvaResourcesTableStreamArn
