package no.unit.nva.cristin.lambda;

import static no.unit.nva.cristin.CristinImportConfig.eventHandlerObjectMapper;
import static no.unit.nva.cristin.lambda.constants.HardcodedValues.HARDCODED_PUBLICATIONS_OWNER;
import static no.unit.nva.cristin.mapper.nva.exceptions.ExceptionHandling.castToCorrectRuntimeException;
import static no.unit.nva.publication.s3imports.ApplicationConstants.MAX_SLEEP_TIME;
import static no.unit.nva.publication.s3imports.FileImportUtils.timestampToString;
import static nva.commons.core.attempt.Try.attempt;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.lambda.runtime.Context;
import com.fasterxml.jackson.databind.JsonNode;
import java.time.Clock;
import java.util.Objects;
import java.util.Optional;
import java.util.Random;
import java.util.UUID;
import no.unit.nva.cristin.mapper.CristinObject;
import no.unit.nva.cristin.mapper.Identifiable;
import no.unit.nva.events.handlers.EventHandler;
import no.unit.nva.events.models.AwsEventBridgeEvent;
import no.unit.nva.events.models.EventReference;
import no.unit.nva.model.AdditionalIdentifier;
import no.unit.nva.model.Publication;
import no.unit.nva.publication.s3imports.ApplicationConstants;
import no.unit.nva.publication.s3imports.FileContentsEvent;
import no.unit.nva.publication.s3imports.FileEntriesEventEmitter;
import no.unit.nva.publication.s3imports.ImportResult;
import no.unit.nva.publication.service.impl.ResourceService;
import no.unit.nva.s3.S3Driver;
import nva.commons.core.JacocoGenerated;
import nva.commons.core.StringUtils;
import nva.commons.core.attempt.Failure;
import nva.commons.core.attempt.Try;
import nva.commons.core.paths.UnixPath;
import nva.commons.core.paths.UriWrapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient;
import software.amazon.awssdk.services.s3.S3Client;

/**
 * Accepts events generated by {@link FileEntriesEventEmitter} with topic equal to
 * {@link FileEntriesEventEmitter#FILE_CONTENTS_EMISSION_EVENT_TOPIC} and subtopic equal to
 * {@link CristinEntryEventConsumer#EVENT_SUBTOPIC}.
 */
public class CristinEntryEventConsumer extends EventHandler<EventReference, Publication> {

    public static final String WRONG_SUBTOPIC_ERROR_TEMPLATE =
        "Unexpected subtopic: %s. Expected subtopic is: %s.";
    public static final int MAX_EFFORTS = 10;
    public static final String ERROR_SAVING_CRISTIN_RESULT = "Could not save cristin result with ID: ";
    public static final Random RANDOM = new Random(System.currentTimeMillis());
    public static final String EVENT_SUBTOPIC = "PublicationService.CristinData.DataEntry";
    public static final String JSON = ".json";
    public static final String UNKNOWN_CRISTIN_ID_ERROR_REPORT_PREFIX = "unknownCristinId_";
    public static final String DO_NOT_WRITE_ID_IN_EXCEPTION_MESSAGE = null;
    public static final UnixPath ERRORS_FOLDER = UnixPath.of("errors");
    public static final UnixPath SUCCESS_FOLDER = UnixPath.of("SUCCESS");

    private static final Logger logger = LoggerFactory.getLogger(CristinEntryEventConsumer.class);
    private static final Clock CLOCK = Clock.systemDefaultZone();

    private final ResourceService resourceService;
    private final S3Client s3Client;

    @JacocoGenerated
    public CristinEntryEventConsumer() {
        this(defaultDynamoDbClient(), defaultS3Client());
    }

    @JacocoGenerated
    protected CristinEntryEventConsumer(AmazonDynamoDB dynamoDbClient, S3Client s3Client) {
        this(new ResourceService(dynamoDbClient, CLOCK),
             s3Client);
    }

    protected CristinEntryEventConsumer(ResourceService resourceService, S3Client s3Client) {
        super(EventReference.class);
        this.resourceService = resourceService;
        this.s3Client = s3Client;
    }

    @Override
    protected Publication processInput(EventReference input,
                                       AwsEventBridgeEvent<EventReference> event,
                                       Context context) {

        validateEvent(event);
        var eventBody = readEventBody(input);
        return attempt(() -> parseCristinObject(eventBody))
                   .map(CristinObject::toPublication)
                   .flatMap(this::persistInDatabase)
                   .map(publication -> storePublicationIdentifierAndCristinIdInS3(publication, eventBody))
                   .orElseThrow(fail -> handleSavingError(fail, eventBody));
    }

    @JacocoGenerated
    private static S3Client defaultS3Client() {
        return S3Client.builder()
                   .httpClient(UrlConnectionHttpClient.create())
                   .build();
    }

    @JacocoGenerated
    private static AmazonDynamoDB defaultDynamoDbClient() {
        return AmazonDynamoDBClientBuilder
                   .standard()
                   .withRegion(ApplicationConstants.AWS_REGION.id())
                   .build();
    }

    private static Optional<String> getCristinIdentifier(Publication publication) {
        return publication.getAdditionalIdentifiers()
                   .stream()
                   .filter(
                       additionalIdentifier -> isCristinAdditionalIdentifier(additionalIdentifier))
                   .findFirst()
                   .map(additionalIdentifier -> additionalIdentifier.getValue());
    }

    private static boolean isCristinAdditionalIdentifier(AdditionalIdentifier additionalIdentifier) {
        return CristinObject.IDENTIFIER_ORIGIN.equals(additionalIdentifier.getSource());
    }

    private Publication storePublicationIdentifierAndCristinIdInS3(Publication publication,
                                                                   FileContentsEvent<JsonNode> eventBody) {
        var cristinIdentifier =
            getCristinIdentifier(publication);
        var fileUri = constructResourcehandleFileUri(eventBody, publication);
        var s3Driver = new S3Driver(s3Client, fileUri.getUri().getHost());
        attempt(() -> s3Driver.insertFile(fileUri.toS3bucketPath(),
                                          cristinIdentifier.orElse(StringUtils.EMPTY_STRING))).orElseThrow();
        return publication;
    }

    private UriWrapper constructResourcehandleFileUri(FileContentsEvent<JsonNode> eventBody, Publication publication) {
        var fileUri = UriWrapper.fromUri(eventBody.getFileUri());
        var timestamp = eventBody.getTimestamp();
        var bucket = fileUri.getHost();
        return bucket
                   .addChild(SUCCESS_FOLDER)
                   .addChild(timestampToString(timestamp))
                   .addChild(publication.getIdentifier().toString());
    }

    private FileContentsEvent<JsonNode> readEventBody(EventReference input) {
        var s3Driver = new S3Driver(s3Client, input.extractBucketName());
        var json = s3Driver.readEvent(input.getUri());
        return FileContentsEvent.fromJson(json, JsonNode.class);
    }

    private CristinObject parseCristinObject(FileContentsEvent<JsonNode> eventBody) {
        CristinObject cristinObject = jsonNodeToCristinObject(eventBody);
        cristinObject.hardcodePublicationOwner(HARDCODED_PUBLICATIONS_OWNER);
        return cristinObject;
    }

    private Identifiable parseIdentifiableObject(FileContentsEvent<JsonNode> event) {
        return attempt(event::getContents)
                   .map(jsonNode -> eventHandlerObjectMapper.convertValue(jsonNode, Identifiable.class))
                   .orElseThrow();
    }

    private CristinObject jsonNodeToCristinObject(FileContentsEvent<JsonNode> event) {
        return attempt(event::getContents)
                   .map(CristinObject::fromJson)
                   .orElseThrow();
    }

    private void validateEvent(AwsEventBridgeEvent<EventReference> event) {
        if (!EVENT_SUBTOPIC.equalsIgnoreCase(event.getDetail().getSubtopic())) {
            String errorMessage = messageIndicatingTheCorrectEventType(event);
            logger.info(event.toJsonString());
            throw new IllegalArgumentException(errorMessage);
        }
    }

    private String messageIndicatingTheCorrectEventType(AwsEventBridgeEvent<EventReference> event) {
        return String.format(WRONG_SUBTOPIC_ERROR_TEMPLATE, event.getDetail().getSubtopic(), EVENT_SUBTOPIC);
    }

    private Try<Publication> persistInDatabase(Publication publication) {
        Try<Publication> attemptSave = tryPersistingInDatabase(publication);

        for (int efforts = 0; shouldTryAgain(attemptSave, efforts); efforts++) {
            attemptSave = tryPersistingInDatabase(publication);

            avoidCongestionInDatabase();
        }
        return attemptSave;
    }

    private boolean shouldTryAgain(Try<Publication> attemptSave, int efforts) {
        return attemptSave.isFailure() && efforts < MAX_EFFORTS;
    }

    private Try<Publication> tryPersistingInDatabase(Publication publication) {
        return attempt(() -> createPublication(publication));
    }

    private Publication createPublication(Publication publication) {
        return resourceService.createPublicationFromImportedEntry(publication);
    }

    private void avoidCongestionInDatabase() {
        int sleepTime = spreadWriteRequests();
        try {
            Thread.sleep(sleepTime);
        } catch (InterruptedException exception) {
            throw new RuntimeException(exception);
        }
    }

    // Randomize waiting time to avoiding creating parallel executions that perform retries in sync.
    private int spreadWriteRequests() {
        return RANDOM.nextInt(MAX_SLEEP_TIME);
    }

    private RuntimeException handleSavingError(Failure<Publication> fail,
                                               FileContentsEvent<JsonNode> eventBody) {
        String cristinObjectId = extractCristinObjectId(eventBody).orElse(DO_NOT_WRITE_ID_IN_EXCEPTION_MESSAGE);
        String errorMessage = ERROR_SAVING_CRISTIN_RESULT + cristinObjectId;
        logger.error(errorMessage, fail.getException());

        saveReportToS3(fail, eventBody);

        return castToCorrectRuntimeException(fail.getException());
    }

    private void saveReportToS3(Failure<Publication> fail,
                                FileContentsEvent<JsonNode> event) {
        var errorFileUri = constructErrorFileUri(event, fail.getException());
        var s3Driver = new S3Driver(s3Client, errorFileUri.getUri().getHost());
        var reportContent = ImportResult.reportFailure(event, fail.getException());
        attempt(() -> s3Driver.insertFile(errorFileUri.toS3bucketPath(), reportContent.toJsonString())).orElseThrow();
    }

    private UriWrapper constructErrorFileUri(FileContentsEvent<JsonNode> event,
                                             Exception exception) {
        var fileUri = UriWrapper.fromUri(event.getFileUri());
        var timestamp = event.getTimestamp();
        var bucket = fileUri.getHost();
        return bucket
                   .addChild(ERRORS_FOLDER)
                   .addChild(timestampToString(timestamp))
                   .addChild(exception.getClass().getSimpleName())
                   .addChild(fileUri.getPath())
                   .addChild(createErrorReportFilename(event));
    }

    private String createErrorReportFilename(FileContentsEvent<JsonNode> eventBody) {
        return extractCristinObjectId(eventBody)
                   .map(idString -> idString + JSON)
                   .orElseGet(this::unknownCristinIdReportFilename);
    }

    private Optional<String> extractCristinObjectId(FileContentsEvent<JsonNode> event) {
        return attempt(() -> parseIdentifiableObject(event))
                   .map(Identifiable::getId)
                   .toOptional()
                   .map(Objects::toString);
    }

    private String unknownCristinIdReportFilename() {
        return UNKNOWN_CRISTIN_ID_ERROR_REPORT_PREFIX + UUID.randomUUID() + JSON;
    }
}
