#Constructs an list of a publications contributors affiliations + nested parents.

PREFIX  nva: <https://nva.sikt.no/ontology/publication#>

CONSTRUCT {
  ?publication nva:contributorOrganization ?parents, ?affiliation  .
  } WHERE {
    SELECT DISTINCT * WHERE {
      ?publication a nva:Publication .
      OPTIONAL {
        [] nva:affiliation ?affiliation .
        FILTER(!ISBLANK(?affiliation))
      }
      OPTIONAL {
        [] nva:partOf ?parents .
        FILTER(!ISBLANK(?parents))
      }
    }
  }
