#Constructs TODO: explain

PREFIX  nva: <https://nva.sikt.no/ontology/publication#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  ?publication nva:nviType ?nviCandidate .
  } WHERE {
  ?publication a nva:Publication .

    ?publication nva:status ?publicationStatus .

    ?publication nva:publishedDate ?publishedDate .

    ?publication nva:entityDescription/nva:reference/nva:publicationInstance/rdf:type ?instanceType .
    #?publication nva:entityDescription/nva:reference/nva:publicationContext/nva:publisher/nva:level ?publisherLevel .
    #?publication nva:entityDescription/nva:reference/nva:publicationContext/nva:series/nva:level ?seriesLevel .
    #?publication nva:entityDescription/nva:reference/nva:publicationContext/nva:journal/nva:level ?journalLevel .

    #BIND(IF (BOUND(?seriesLevel), ?seriesLevel, ?publisherLevel) AS ?seriesOrPublisherLevel)

    #BIND(IF (BOUND(?seriesOrPublisherLevel), ?seriesOrPublisherLevel, ?journalLevel) AS ?level)

    BIND(IF (?publishedDate > "2023-01-01T00:00:00+00:00"^^xsd:dateTime
             && ?publishedDate < "2023-12-31T23:59:59+00:00"^^xsd:dateTime,
             "true"^^xsd:boolean, "false"^^xsd:boolean) AS ?publishedInCurrentYear)

    BIND(IF (?instanceType = nva:AcademicMonograph
             || ?instanceType = nva:AcademicChapter
             || ?instanceType = nva:AcademicArticle
             || ?instanceType = nva:AcademicLiteratureReview, "true"^^xsd:boolean, "false"^^xsd:boolean) AS ?isNviInstance)

    #BIND(IF(?publicationStatus = nva:PUBLISHED
    #         && ?isNviInstance = "true"^^xsd:boolean
    #         && (?level = "1" || ?level = "2"), nva:NviCandidate, nva:NonNviCandidate)  AS ?nviCandidate)

    BIND(IF(?publicationStatus = nva:PUBLISHED
      && ?isNviInstance = "true"^^xsd:boolean
      && ?publishedInCurrentYear = "true"^^xsd:boolean, nva:NviCandidate, nva:NonNviCandidate)  AS ?nviCandidate)
}