#Constructs an organization with a topLevelAffiliation field determined by recursively looking in
#the orgs partOf-field until an org isn't part of another org.

PREFIX  nva: <https://nva.sikt.no/ontology/publication#>

CONSTRUCT {
  ?publication nva:topLevelOrganization ?top_org .
  } WHERE {
  ?publication a nva:Publication .
  ?affiliation nva:affiliation ?org .
  ?org nva:partOf* ?top_org .
  FILTER NOT EXISTS { ?top_org nva:partOf ?e } .
  FILTER ( strstarts(str(?org), "http") ) .
}