#Constructs an organization with a topLevelAffiliation field determined by recursively looking in
#the orgs partOf-field until an org isn't part of another org.

PREFIX  organization: <https://bibsysdev.github.io/src/nva/ontology.ttl#>

CONSTRUCT {
  ?org organization:topLevelOrganization ?top_org .
  } WHERE {
  ?org a organization:Organization ;
    organization:partOf* ?top_org .
    FILTER NOT EXISTS { ?top_org organization:partOf ?e } .
}