dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.aws.lambda.events)
    api(nvaCatalog.aws.sdk2.s3)
    api(nvaCatalog.jackson.annotations)
    implementation(libs.pdfbox)
    implementation(libs.poi)
    implementation(libs.tika.core)
    implementation(libs.tika.parser.pdf.module)
    implementation(nvaCatalog.aws.sdk2.sdk.core)
    implementation(nvaCatalog.jackson.databind)
    implementation(nvaCatalog.slf4j.api)
    implementation(nvaLibs.core)
    implementation(nvaLibs.s3)
    runtimeOnly(libs.tika.parsers.standard)
    runtimeOnly(nvaCatalog.aws.sdk2.urlconnection)

    testImplementation(libs.poi.ooxml)
    testImplementation(nvaCatalog.assertj.core)
    testImplementation(nvaCatalog.jackson.core)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.junit.jupiter.params)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaLibs.testutils)
}

test {
    environment "NVA_PERSISTED_STORAGE_BUCKET_NAME", "source-bucket"
    environment "TEXT_STORAGE_BUCKET_NAME", "text-bucket"
    environment "AWS_REGION", "eu-west-1"
}
