package no.unit.nva;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import no.unit.nva.commons.json.JsonUtils;
import no.unit.nva.model.Publication;
import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.core.Is.is;

@Deprecated
class ChapterToAnthologyMigrationTest {

    public static final ObjectMapper MAPPER = JsonUtils.dtoObjectMapper;
    public static final String CONTEXT_TYPE_POINTER = "/entityDescription/reference/publicationContext/type";
    public static final String CONTEXT_ID_POINTER = "/entityDescription/reference/publicationContext/id";
    public static final String CONTEXT_PART_OF_POINTER = "/entityDescription/reference/publicationContext/partOf";

    @Test
    void shouldReturnAnthologyWhenChapterIsConsumed() throws JsonProcessingException {
        var publicationJson = getOldStyleChapterArticle();
        var publication = MAPPER.readValue(publicationJson, Publication.class);
        var reSerializedPublication = MAPPER.writeValueAsString(publication);
        var json = MAPPER.readTree(reSerializedPublication);
        var contextTypeString = json.at(CONTEXT_TYPE_POINTER).textValue();
        var originalJson = MAPPER.readTree(publicationJson);
        var partOfFromOriginalJson = originalJson.at(CONTEXT_PART_OF_POINTER).textValue();
        var idValue = json.at(CONTEXT_ID_POINTER).textValue();
        assertThat(contextTypeString, is(equalTo("Anthology")));
        assertThat(idValue, is(equalTo(partOfFromOriginalJson)));
    }

    private String getOldStyleChapterArticle() {
        return "{\n"
                + "  \"type\" : \"Publication\",\n"
                + "  \"identifier\" : \"c443030e-9d56-43d8-afd1-8c89105af555\",\n"
                + "  \"status\" : \"NEW\",\n"
                + "  \"resourceOwner\" : {\n"
                + "    \"owner\" : \"JHVKQ0YmGXxBs\",\n"
                + "    \"ownerAffiliation\" : \"https://www.example.org/voluptatemet\"\n"
                + "  },\n"
                + "  \"publisher\" : {\n"
                + "    \"type\" : \"Organization\",\n"
                + "    \"id\" : \"https://www.example.org/commodiinventore\",\n"
                + "    \"labels\" : {\n"
                + "      \"se\" : \"VDNncQpOHGJFP3M\"\n"
                + "    }\n"
                + "  },\n"
                + "  \"createdDate\" : \"2006-07-14T18:34:40.074Z\",\n"
                + "  \"modifiedDate\" : \"1985-08-02T04:24:27.393Z\",\n"
                + "  \"publishedDate\" : \"1983-07-03T05:05:41.641Z\",\n"
                + "  \"indexedDate\" : \"1976-11-15T15:49:32.984Z\",\n"
                + "  \"handle\" : \"https://www.example.org/beataeautem\",\n"
                + "  \"doi\" : \"https://doi.org/10.1234/ut\",\n"
                + "  \"link\" : \"https://www.example.org/culpaillum\",\n"
                + "  \"entityDescription\" : {\n"
                + "    \"type\" : \"EntityDescription\",\n"
                + "    \"mainTitle\" : \"c5A392MJB24nOcoUPJs\",\n"
                + "    \"alternativeTitles\" : {\n"
                + "      \"el\" : \"skls3rTT2pUYfkSH\"\n"
                + "    },\n"
                + "    \"language\" : \"http://lexvo.org/id/iso639-3/und\",\n"
                + "    \"publicationDate\" : {\n"
                + "      \"type\" : \"PublicationDate\",\n"
                + "      \"year\" : \"RVKiwCLLffHfTjT6U\",\n"
                + "      \"month\" : \"mFeorgPDgOI\",\n"
                + "      \"day\" : \"vq24YDP2MW6dNC1U3\"\n"
                + "    },\n"
                + "    \"contributors\" : [ {\n"
                + "      \"type\" : \"Contributor\",\n"
                + "      \"identity\" : {\n"
                + "        \"type\" : \"Identity\",\n"
                + "        \"id\" : \"https://www.example.com/DNzDixSR7S8obn8\",\n"
                + "        \"name\" : \"V0O7LUMu69N\",\n"
                + "        \"nameType\" : \"Personal\",\n"
                + "        \"orcId\" : \"AYV7plbQ9uBm5\"\n"
                + "      },\n"
                + "      \"affiliations\" : [ {\n"
                + "        \"type\" : \"Organization\",\n"
                + "        \"id\" : \"https://www.example.com/nOAjNoqoWvtu6bpCcg\",\n"
                + "        \"labels\" : {\n"
                + "          \"it\" : \"SEB7CSKHOcuZ0xItH\"\n"
                + "        }\n"
                + "      } ],\n"
                + "      \"role\" : {\n"
                + "        \"type\" : \"Sponsor\"\n"
                + "      },\n"
                + "      \"sequence\" : 2,\n"
                + "      \"correspondingAuthor\" : false\n"
                + "    }, {\n"
                + "      \"type\" : \"Contributor\",\n"
                + "      \"identity\" : {\n"
                + "        \"type\" : \"Identity\",\n"
                + "        \"id\" : \"https://www.example.com/erfBz21D09\",\n"
                + "        \"name\" : \"ddHz9xckMkqe\",\n"
                + "        \"nameType\" : \"Personal\",\n"
                + "        \"orcId\" : \"BwB2S6OMJNxVH\"\n"
                + "      },\n"
                + "      \"affiliations\" : [ {\n"
                + "        \"type\" : \"Organization\",\n"
                + "        \"id\" : \"https://www.example.com/kMofSykKZAju0pwoZLY\",\n"
                + "        \"labels\" : {\n"
                + "          \"el\" : \"Ze40vzYXvBrS2\"\n"
                + "        }\n"
                + "      } ],\n"
                + "      \"role\" : {\n"
                + "        \"type\" : \"Director\"\n"
                + "      },\n"
                + "      \"sequence\" : 9,\n"
                + "      \"correspondingAuthor\" : false\n"
                + "    } ],\n"
                + "    \"alternativeAbstracts\" : {\n"
                + "      \"nn\" : \"agZrq06stR3M7\"\n"
                + "    },\n"
                + "    \"npiSubjectHeading\" : \"21n9bgMsFSG\",\n"
                + "    \"tags\" : [ \"8ECIDaMr4VRjJcKn5\" ],\n"
                + "    \"description\" : \"Db7EOlIicAtg\",\n"
                + "    \"reference\" : {\n"
                + "      \"type\" : \"Reference\",\n"
                + "      \"publicationContext\" : {\n"
                + "        \"type\" : \"Chapter\",\n"
                + "        \"partOf\" : \"https://www.example.com/Uid7iMyjiPz\"\n"
                + "      },\n"
                + "      \"doi\" : \"https://www.example.com/n2xcJHD9cE39S\",\n"
                + "      \"publicationInstance\" : {\n"
                + "        \"type\" : \"AcademicChapter\",\n"
                + "        \"pages\" : {\n"
                + "          \"type\" : \"Range\",\n"
                + "          \"begin\" : \"pJQ7S8NMps4mBRi\",\n"
                + "          \"end\" : \"i8B0WYS8RkG6LBS\"\n"
                + "        }\n"
                + "      }\n"
                + "    },\n"
                + "    \"metadataSource\" : \"https://www.example.com/CJ9UAv5pUFS\",\n"
                + "    \"abstract\" : \"wxQIaFbeSqlnrAiXMO\"\n"
                + "  },\n"
                + "  \"projects\" : [ {\n"
                + "    \"type\" : \"ResearchProject\",\n"
                + "    \"id\" : \"https://www.example.org/utducimus\",\n"
                + "    \"name\" : \"ZrCbRSj60Z4sV\",\n"
                + "    \"approvals\" : [ {\n"
                + "      \"type\" : \"Approval\",\n"
                + "      \"approvalDate\" : \"1982-07-06T19:16:35.048Z\",\n"
                + "      \"approvedBy\" : \"DIRHEALTH\",\n"
                + "      \"approvalStatus\" : \"APPROVED\",\n"
                + "      \"applicationCode\" : \"0Sxhgqbu4rJ9Z\"\n"
                + "    } ]\n"
                + "  } ],\n"
                + "  \"fundings\" : [ {\n"
                + "    \"type\" : \"UnconfirmedFunding\",\n"
                + "    \"source\" : \"https://www.example.org/quonostrum\",\n"
                + "    \"identifier\" : \"JZySTJMPtL\",\n"
                + "    \"labels\" : {\n"
                + "      \"cs\" : \"uKhdonvAbC\"\n"
                + "    },\n"
                + "    \"fundingAmount\" : {\n"
                + "      \"currency\" : \"USD\",\n"
                + "      \"amount\" : 482098828\n"
                + "    },\n"
                + "    \"activeFrom\" : \"1997-01-20T02:50:31.114Z\",\n"
                + "    \"activeTo\" : \"2000-02-21T01:59:17.108Z\"\n"
                + "  }, {\n"
                + "    \"type\" : \"ConfirmedFunding\",\n"
                + "    \"source\" : \"https://www.example.org/molestiaeea\",\n"
                + "    \"id\" : \"https://www.example.org/voluptatemlabore\",\n"
                + "    \"identifier\" : \"sh58GW54kMmQs\",\n"
                + "    \"labels\" : {\n"
                + "      \"fi\" : \"5aoPas1T00HA5Qx871M\"\n"
                + "    },\n"
                + "    \"fundingAmount\" : {\n"
                + "      \"currency\" : \"GBP\",\n"
                + "      \"amount\" : 555290777\n"
                + "    },\n"
                + "    \"activeFrom\" : \"2007-05-10T04:45:18.559Z\",\n"
                + "    \"activeTo\" : \"2014-02-05T19:44:00.200Z\"\n"
                + "  } ],\n"
                + "  \"additionalIdentifiers\" : [ {\n"
                + "    \"type\" : \"AdditionalIdentifier\",\n"
                + "    \"source\" : \"fakesource\",\n"
                + "    \"value\" : \"1234\"\n"
                + "  } ],\n"
                + "  \"subjects\" : [ \"https://www.example.org/eaut\" ],\n"
                + "  \"associatedArtifacts\" : [ {\n"
                + "    \"type\" : \"PublishedFile\",\n"
                + "    \"identifier\" : \"f2211b09-5685-45cb-a095-507055f1415f\",\n"
                + "    \"name\" : \"ldNNzZW1iRJ5cZ\",\n"
                + "    \"mimeType\" : \"cjpQQj3Kz7n988gO7\",\n"
                + "    \"size\" : 1535093502,\n"
                + "    \"license\" : {\n"
                + "      \"type\" : \"License\",\n"
                + "      \"identifier\" : \"6B1XaWdYH5W5eInl\",\n"
                + "      \"labels\" : {\n"
                + "        \"is\" : \"zAr3s1Om8f0TwIJ\"\n"
                + "      },\n"
                + "      \"link\" : \"https://www.example.com/roOE79baBYiyT6yn\"\n"
                + "    },\n"
                + "    \"administrativeAgreement\" : false,\n"
                + "    \"publisherAuthority\" : true,\n"
                + "    \"publishedDate\" : \"1978-04-26T01:36:50.079Z\",\n"
                + "    \"visibleForNonOwner\" : true\n"
                + "  }, {\n"
                + "    \"type\" : \"AssociatedLink\",\n"
                + "    \"id\" : \"https://www.example.com/sCp3rnsd0HLDN7UdvE\",\n"
                + "    \"name\" : \"MIAspdy8Iq\",\n"
                + "    \"description\" : \"wkepxUA45yXHE\"\n"
                + "  } ],\n"
                + "  \"rightsHolder\" : \"lY3n3MmJry\",\n"
                + "  \"modelVersion\" : \"0.20.10\"\n"
                + "}";
    }
}
