package no.unit.nva;

import no.unit.nva.commons.json.JsonUtils;
import no.unit.nva.model.Publication;
import no.unit.nva.model.instancetypes.book.BookMonographContentType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

import static nva.commons.core.attempt.Try.attempt;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.Is.is;
import static org.hamcrest.core.IsEqual.equalTo;

@Deprecated
class MigrationBookMonographSubtypesTest {
    @ParameterizedTest
    @EnumSource(BookMonographContentType.class)
    @Disabled
    void shouldDeserializeOldSubtypeBookMonographContentTypeAsType(BookMonographContentType content) {
        var type = content.getValue();
        var json = generateFullBookMonographWithContentType(type);
        var bookMonograph = attempt(() -> JsonUtils.dtoObjectMapper.readValue(json, Publication.class))
                .orElseThrow();
        var actual = bookMonograph.getEntityDescription()
                .getReference().getPublicationInstance().getClass().getSimpleName();
        assertThat(actual, is(equalTo(type)));
    }

    private String generateFullBookMonographWithContentType(String type) {
        return "{\n"
                + "  \"type\" : \"Publication\",\n"
                + "  \"identifier\" : \"c443030e-9d56-43d8-afd1-8c89105af555\",\n"
                + "  \"status\" : \"NEW\",\n"
                + "  \"resourceOwner\" : {\n"
                + "    \"owner\" : \"tB62sIFYKg\",\n"
                + "    \"ownerAffiliation\" : \"https://www.example.org/commodiut\"\n"
                + "  },\n"
                + "  \"publisher\" : {\n"
                + "    \"type\" : \"Organization\",\n"
                + "    \"id\" : \"https://www.example.org/suscipitat\",\n"
                + "    \"labels\" : {\n"
                + "      \"ru\" : \"mrH4HAV6aEDjGNRJ2\"\n"
                + "    }\n"
                + "  },\n"
                + "  \"createdDate\" : \"1972-05-08T00:12:05.315Z\",\n"
                + "  \"modifiedDate\" : \"2019-09-28T13:25:15.960Z\",\n"
                + "  \"publishedDate\" : \"1975-01-08T02:19:20.777Z\",\n"
                + "  \"indexedDate\" : \"2007-03-21T06:29:45.706Z\",\n"
                + "  \"handle\" : \"https://www.example.org/expeditaaliquam\",\n"
                + "  \"doi\" : \"https://doi.org/10.1234/voluptas\",\n"
                + "  \"link\" : \"https://www.example.org/hicsoluta\",\n"
                + "  \"entityDescription\" : {\n"
                + "    \"type\" : \"EntityDescription\",\n"
                + "    \"mainTitle\" : \"TJiBWzUbcYOsg1Bh6ar\",\n"
                + "    \"alternativeTitles\" : {\n"
                + "      \"pl\" : \"u6W8XtFlErl7CT20H\"\n"
                + "    },\n"
                + "    \"language\" : \"http://lexvo.org/id/iso639-3/und\",\n"
                + "    \"date\" : {\n"
                + "      \"type\" : \"PublicationDate\",\n"
                + "      \"year\" : \"tYcREtuLoDw5l9YZV\",\n"
                + "      \"month\" : \"gMzfA9CfARP0qdRT\",\n"
                + "      \"day\" : \"EiJQbxbLQZj\"\n"
                + "    },\n"
                + "    \"contributors\" : [ {\n"
                + "      \"type\" : \"Contributor\",\n"
                + "      \"identity\" : {\n"
                + "        \"type\" : \"Identity\",\n"
                + "        \"id\" : \"https://www.example.com/GqttyV980NRYL8Pfp\",\n"
                + "        \"name\" : \"rA6GkyIRJGv2di\",\n"
                + "        \"nameType\" : \"Personal\",\n"
                + "        \"orcId\" : \"9DtRI5qSVrxx\"\n"
                + "      },\n"
                + "      \"affiliations\" : [ {\n"
                + "        \"type\" : \"Organization\",\n"
                + "        \"id\" : \"https://www.example.com/O9IL4Q16jMMTmyFa\",\n"
                + "        \"labels\" : {\n"
                + "          \"af\" : \"A3H5OIKOwrqriOct\"\n"
                + "        }\n"
                + "      } ],\n"
                + "      \"role\" : \"ContactPerson\",\n"
                + "      \"sequence\" : 7,\n"
                + "      \"correspondingAuthor\" : false\n"
                + "    }, {\n"
                + "      \"type\" : \"Contributor\",\n"
                + "      \"identity\" : {\n"
                + "        \"type\" : \"Identity\",\n"
                + "        \"id\" : \"https://www.example.com/Ele611kKvbKnqeL\",\n"
                + "        \"name\" : \"TIE6zIiWCWLpfvK\",\n"
                + "        \"nameType\" : \"Organizational\",\n"
                + "        \"orcId\" : \"aJ1pvnZ8FVOh5\"\n"
                + "      },\n"
                + "      \"affiliations\" : [ {\n"
                + "        \"type\" : \"Organization\",\n"
                + "        \"id\" : \"https://www.example.com/CszMv40Wx2OX\",\n"
                + "        \"labels\" : {\n"
                + "          \"af\" : \"CCP5RUwJlFTQTzL\"\n"
                + "        }\n"
                + "      } ],\n"
                + "      \"role\" : \"Dramatist\",\n"
                + "      \"sequence\" : 0,\n"
                + "      \"correspondingAuthor\" : false\n"
                + "    } ],\n"
                + "    \"npiSubjectHeading\" : \"RCjSANi9tVDH0X1lEN\",\n"
                + "    \"tags\" : [ \"gyNAMEiHlZuJT\" ],\n"
                + "    \"description\" : \"TBlPsIoaVroQdh\",\n"
                + "    \"reference\" : {\n"
                + "      \"type\" : \"Reference\",\n"
                + "      \"publicationContext\" : {\n"
                + "        \"type\" : \"Book\",\n"
                + "        \"series\" : {\n"
                + "          \"type\" : \"Series\",\n"
                + "          \"id\" : \"https://api.dev.nva.aws.unit.no/publication-channels/gTApbmIXv6\"\n"
                + "        },\n"
                + "        \"seriesNumber\" : \"wmHi1PgzWPm86KCe6\",\n"
                + "        \"publisher\" : {\n"
                + "          \"type\" : \"Publisher\",\n"
                + "          \"id\" : \"https://api.dev.nva.aws.unit.no/publication-channels/rLViYfagIJ\"\n"
                + "        },\n"
                + "        \"isbnList\" : [ \"9790094516099\" ]\n"
                + "      },\n"
                + "      \"doi\" : \"https://www.example.com/FbubVFoXuT\",\n"
                + "      \"publicationInstance\" : {\n"
                + "        \"type\" : \"BookMonograph\",\n"
                + "        \"contentType\" : \"" + type + "\",\n"
                + "        \"originalResearch\" : false,\n"
                + "        \"peerReviewed\" : false,\n"
                + "        \"pages\" : {\n"
                + "          \"type\" : \"MonographPages\",\n"
                + "          \"introduction\" : {\n"
                + "            \"type\" : \"Range\",\n"
                + "            \"begin\" : \"9n2jMU0p6vPI9pcqQyi\",\n"
                + "            \"end\" : \"QAYvjiCUvm\"\n"
                + "          },\n"
                + "          \"pages\" : \"rXSsjeWG62j\",\n"
                + "          \"illustrated\" : false\n"
                + "        }\n"
                + "      }\n"
                + "    },\n"
                + "    \"metadataSource\" : \"https://www.example.com/TJrqCkHQVrIt0j\",\n"
                + "    \"abstract\" : \"TRcbF8cf89PgTuBk\"\n"
                + "  },\n"
                + "  \"projects\" : [ {\n"
                + "    \"type\" : \"ResearchProject\",\n"
                + "    \"id\" : \"https://www.example.org/perferendisharum\",\n"
                + "    \"name\" : \"ESFpOgIIS4q9dW6\",\n"
                + "    \"approvals\" : [ {\n"
                + "      \"type\" : \"Approval\",\n"
                + "      \"date\" : \"1993-11-28T10:21:43.195Z\",\n"
                + "      \"approvedBy\" : \"NARA\",\n"
                + "      \"approvalStatus\" : \"APPLIED\",\n"
                + "      \"applicationCode\" : \"UZlpisZwYl0NJVz6lLy\"\n"
                + "    } ]\n"
                + "  } ],\n"
                + "  \"fundings\" : [ {\n"
                + "    \"type\" : \"UnconfirmedFunding\",\n"
                + "    \"source\" : \"https://www.example.org/eamagnam\",\n"
                + "    \"identifier\" : \"0kIBfGDot4QwO2kb\",\n"
                + "    \"labels\" : {\n"
                + "      \"it\" : \"JF3ZSl24zL\"\n"
                + "    },\n"
                + "    \"fundingAmount\" : {\n"
                + "      \"currency\" : \"USD\",\n"
                + "      \"amount\" : 1138272242\n"
                + "    },\n"
                + "    \"activeFrom\" : \"2003-11-07T09:15:50.695Z\",\n"
                + "    \"activeTo\" : \"2015-08-01T19:20:16.941Z\"\n"
                + "  }, {\n"
                + "    \"type\" : \"ConfirmedFunding\",\n"
                + "    \"source\" : \"https://www.example.org/fugiatsapiente\",\n"
                + "    \"id\" : \"https://www.example.org/suntmagni\",\n"
                + "    \"identifier\" : \"BNo5moC50NfbNBo\",\n"
                + "    \"labels\" : {\n"
                + "      \"sv\" : \"q7am4xSOFZpHduBza\"\n"
                + "    },\n"
                + "    \"fundingAmount\" : {\n"
                + "      \"currency\" : \"EUR\",\n"
                + "      \"amount\" : 873582428\n"
                + "    },\n"
                + "    \"activeFrom\" : \"1974-04-25T00:39:51.618Z\",\n"
                + "    \"activeTo\" : \"2018-06-05T01:03:44.768Z\"\n"
                + "  } ],\n"
                + "  \"additionalIdentifiers\" : [ {\n"
                + "    \"type\" : \"AdditionalIdentifier\",\n"
                + "    \"source\" : \"fakesource\",\n"
                + "    \"value\" : \"1234\"\n"
                + "  } ],\n"
                + "  \"subjects\" : [ \"https://www.example.org/quaeratdolorem\" ],\n"
                + "  \"associatedArtifacts\" : [ {\n"
                + "    \"type\" : \"PublishedFile\",\n"
                + "    \"identifier\" : \"86406e82-636e-4ddb-8e07-fd6619ec3aa0\",\n"
                + "    \"name\" : \"bNvv7O5PyKT\",\n"
                + "    \"mimeType\" : \"gVDXmTw9H2gqBRm\",\n"
                + "    \"size\" : 838225864,\n"
                + "    \"license\" : {\n"
                + "      \"type\" : \"License\",\n"
                + "      \"identifier\" : \"Y1VBFAUQrmps39Lg\",\n"
                + "      \"labels\" : {\n"
                + "        \"bg\" : \"uhHKMW0QVPFmPcluDo\"\n"
                + "      },\n"
                + "      \"link\" : \"https://www.example.com/LwqTEw9Ulq\"\n"
                + "    },\n"
                + "    \"administrativeAgreement\" : false,\n"
                + "    \"publisherAuthority\" : true,\n"
                + "    \"visibleForNonOwner\" : true\n"
                + "  }, {\n"
                + "    \"type\" : \"AssociatedLink\",\n"
                + "    \"id\" : \"https://www.example.com/qlvWdNWNyFWfvk5qg6X\",\n"
                + "    \"name\" : \"Otvp1638EBdF0mJ\",\n"
                + "    \"description\" : \"ewjrLNbRKEdzqKM\"\n"
                + "  } ],\n"
                + "  \"modelVersion\" : \"0.19.29\"\n"
                + "}";
    }
}
