package no.unit.nva;

import no.unit.nva.commons.json.JsonUtils;
import no.unit.nva.model.Publication;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

@Deprecated
class MusicPerformanceMediaTypeOtherMigrationTest {

    @Test
    void shouldNotThrowWhenInputIsOldStyleMusicPerformance() {
        assertDoesNotThrow(() -> JsonUtils.dtoObjectMapper.readValue(getPublicationJson(), Publication.class));
    }

    private String getPublicationJson() {
        return "{\n"
               + "  \"type\" : \"Publication\",\n"
               + "  \"identifier\" : \"c443030e-9d56-43d8-afd1-8c89105af555\",\n"
               + "  \"status\" : \"DRAFT\",\n"
               + "  \"resourceOwner\" : {\n"
               + "    \"owner\" : \"AjIDQ1O1O1I00PNLpRy\",\n"
               + "    \"ownerAffiliation\" : \"https://www.example.org/autemvoluptatibus\"\n"
               + "  },\n"
               + "  \"publisher\" : {\n"
               + "    \"type\" : \"Organization\",\n"
               + "    \"id\" : \"https://www.example.org/quasiut\",\n"
               + "    \"labels\" : {\n"
               + "      \"it\" : \"n7M0zVEYv1OnNmiGP\"\n"
               + "    }\n"
               + "  },\n"
               + "  \"createdDate\" : \"2015-01-22T18:44:40.590Z\",\n"
               + "  \"modifiedDate\" : \"2020-04-24T00:20:28.738Z\",\n"
               + "  \"publishedDate\" : \"1987-07-06T07:50:22.069Z\",\n"
               + "  \"indexedDate\" : \"1988-09-20T11:12:40.748Z\",\n"
               + "  \"handle\" : \"https://www.example.org/odiosit\",\n"
               + "  \"doi\" : \"https://doi.org/10.1234/excepturi\",\n"
               + "  \"link\" : \"https://www.example.org/doloresblanditiis\",\n"
               + "  \"entityDescription\" : {\n"
               + "    \"type\" : \"EntityDescription\",\n"
               + "    \"mainTitle\" : \"J8DTohwUcOklXJiMUU\",\n"
               + "    \"alternativeTitles\" : {\n"
               + "      \"ca\" : \"fyL9TQk95S0c5oNJmQ\"\n"
               + "    },\n"
               + "    \"language\" : \"http://lexvo.org/id/iso639-3/und\",\n"
               + "    \"publicationDate\" : {\n"
               + "      \"type\" : \"PublicationDate\",\n"
               + "      \"year\" : \"P8hR6d1XS7\",\n"
               + "      \"month\" : \"xkCJIBqAW9VAKPC\",\n"
               + "      \"day\" : \"Aqc3HzlZJbAmPXtr\"\n"
               + "    },\n"
               + "    \"contributors\" : [ {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"id\" : \"https://www.example.com/TVrP3hMtYsZWlsO1\",\n"
               + "        \"name\" : \"M9xLUAFtraiqfLLl\",\n"
               + "        \"nameType\" : \"Personal\",\n"
               + "        \"orcId\" : \"hLOxl74QrP2u5MhU\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ {\n"
               + "        \"type\" : \"Organization\",\n"
               + "        \"id\" : \"https://www.example.com/381L4DOxksvfybkks\",\n"
               + "        \"labels\" : {\n"
               + "          \"se\" : \"CdA4PH3AlwJFxa\"\n"
               + "        }\n"
               + "      } ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"Dramaturge\"\n"
               + "      },\n"
               + "      \"sequence\" : 8,\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    }, {\n"
               + "      \"type\" : \"Contributor\",\n"
               + "      \"identity\" : {\n"
               + "        \"type\" : \"Identity\",\n"
               + "        \"id\" : \"https://www.example.com/PbrHuDQOzSRtmuef9\",\n"
               + "        \"name\" : \"jJyp1OtUgpWmvB\",\n"
               + "        \"nameType\" : \"Personal\",\n"
               + "        \"orcId\" : \"gujyeUKURIqdMv\"\n"
               + "      },\n"
               + "      \"affiliations\" : [ {\n"
               + "        \"type\" : \"Organization\",\n"
               + "        \"id\" : \"https://www.example.com/HJVbwiX3vS05Lo\",\n"
               + "        \"labels\" : {\n"
               + "          \"af\" : \"swmvyMr2rfd1Q\"\n"
               + "        }\n"
               + "      } ],\n"
               + "      \"role\" : {\n"
               + "        \"type\" : \"LandscapeArchitect\"\n"
               + "      },\n"
               + "      \"sequence\" : 8,\n"
               + "      \"correspondingAuthor\" : false\n"
               + "    } ],\n"
               + "    \"alternativeAbstracts\" : {\n"
               + "      \"sv\" : \"GOkiRDyoCvEHrqNQ\"\n"
               + "    },\n"
               + "    \"npiSubjectHeading\" : \"9FgcTyZGVBtuRbNi\",\n"
               + "    \"tags\" : [ \"EDHejpacSYi4s\" ],\n"
               + "    \"description\" : \"cD0zH4qmsPxZ1BFXYH\",\n"
               + "    \"reference\" : {\n"
               + "      \"type\" : \"Reference\",\n"
               + "      \"publicationContext\" : {\n"
               + "        \"type\" : \"Artistic\"\n"
               + "      },\n"
               + "      \"doi\" : \"https://www.example.com/T6x16abk4tL9pJmcP\",\n"
               + "      \"publicationInstance\" : {\n"
               + "        \"type\" : \"MusicPerformance\",\n"
               + "        \"manifestations\" : [ {\n"
               + "          \"type\" : \"AudioVisualPublication\",\n"
               + "          \"mediaType\" : {\n"
               + "            \"type\" : \"Other\"\n"
               + "          },\n"
               + "          \"publisher\" : {\n"
               + "            \"type\" : \"UnconfirmedPublisher\",\n"
               + "            \"name\" : \"QDnCXSXohy6izCtYz\"\n"
               + "          },\n"
               + "          \"catalogueNumber\" : \"hLO9aj1UEmV\",\n"
               + "          \"trackList\" : [ {\n"
               + "            \"type\" : \"MusicTrack\",\n"
               + "            \"title\" : \"ca7fNcv2wEWBqb\",\n"
               + "            \"composer\" : \"5cEsP3hKwZ\",\n"
               + "            \"extent\" : \"XqemkynVCcK\"\n"
               + "          } ],\n"
               + "          \"isrc\" : {\n"
               + "            \"type\" : \"Isrc\",\n"
               + "            \"value\" : \"USRC17607839\"\n"
               + "          }\n"
               + "        }, {\n"
               + "          \"type\" : \"Concert\",\n"
               + "          \"place\" : {\n"
               + "            \"type\" : \"UnconfirmedPlace\",\n"
               + "            \"label\" : \"mIX65ojtv27IykDz\",\n"
               + "            \"country\" : \"MHmhcjJ6GqJt\"\n"
               + "          },\n"
               + "          \"time\" : {\n"
               + "            \"type\" : \"Period\",\n"
               + "            \"from\" : \"2013-09-22T11:48:16.812Z\",\n"
               + "            \"to\" : \"2021-01-07T08:00:36.760Z\"\n"
               + "          },\n"
               + "          \"extent\" : \"ZCdL0KBDNBWs9\",\n"
               + "          \"description\" : \"lf9dHe3iscz\",\n"
               + "          \"concertProgramme\" : [ {\n"
               + "            \"type\" : \"MusicalWorkPerformance\",\n"
               + "            \"title\" : \"1bela5whi2OUr\",\n"
               + "            \"composer\" : \"Zi2aoj5jphaeU\",\n"
               + "            \"premiere\" : true\n"
               + "          } ],\n"
               + "          \"concertSeries\" : \"ump2H4rqCg8sV3XkcU\"\n"
               + "        }, {\n"
               + "          \"type\" : \"MusicScore\",\n"
               + "          \"ensemble\" : \"kuSQ2vyLF2rzd6XG\",\n"
               + "          \"movements\" : \"dnPQUlyJZKd8b\",\n"
               + "          \"extent\" : \"bKwpokEhl6lLOo\",\n"
               + "          \"publisher\" : {\n"
               + "            \"type\" : \"UnconfirmedPublisher\",\n"
               + "            \"name\" : \"feMH1djW2nupX\"\n"
               + "          },\n"
               + "          \"ismn\" : {\n"
               + "            \"type\" : \"Ismn\",\n"
               + "            \"value\" : \"M230671187\",\n"
               + "            \"formatted\" : \"M-2306-7118-7\"\n"
               + "          }\n"
               + "        }, {\n"
               + "          \"type\" : \"OtherPerformance\",\n"
               + "          \"performanceType\" : \"V0eQev2BIVCM\",\n"
               + "          \"place\" : {\n"
               + "            \"type\" : \"UnconfirmedPlace\",\n"
               + "            \"label\" : \"FjNsieWYjD\",\n"
               + "            \"country\" : \"pDO8DpR8MPsjT7St\"\n"
               + "          },\n"
               + "          \"extent\" : \"Y0QeX1F4k7oB2xtfXFs\",\n"
               + "          \"musicalWorks\" : [ {\n"
               + "            \"type\" : \"MusicalWork\",\n"
               + "            \"title\" : \"IchLc2M3327Rn\",\n"
               + "            \"composer\" : \"Llh4Jr7pi82f\"\n"
               + "          } ]\n"
               + "        } ],\n"
               + "        \"pages\" : {\n"
               + "          \"type\" : \"NullPages\"\n"
               + "        }\n"
               + "      }\n"
               + "    },\n"
               + "    \"metadataSource\" : \"https://www.example.com/G4m84dkZ1Jcq5I\",\n"
               + "    \"abstract\" : \"SR8x0E5wJ0jzEyVHl\"\n"
               + "  },\n"
               + "  \"projects\" : [ {\n"
               + "    \"type\" : \"ResearchProject\",\n"
               + "    \"id\" : \"https://www.example.org/autquia\",\n"
               + "    \"name\" : \"5ZDI2NA3OvcHgp\",\n"
               + "    \"approvals\" : [ {\n"
               + "      \"type\" : \"Approval\",\n"
               + "      \"approvalDate\" : \"2012-09-07T10:46:29.746Z\",\n"
               + "      \"approvedBy\" : \"NMA\",\n"
               + "      \"approvalStatus\" : \"NOTAPPLIED\",\n"
               + "      \"applicationCode\" : \"3bPyvZYPPN3\"\n"
               + "    } ]\n"
               + "  } ],\n"
               + "  \"fundings\" : [ {\n"
               + "    \"type\" : \"UnconfirmedFunding\",\n"
               + "    \"source\" : \"https://www.example.org/quisaliquam\",\n"
               + "    \"identifier\" : \"NZ0PfAE00F0yZDNUL\",\n"
               + "    \"labels\" : {\n"
               + "      \"pl\" : \"wu0f1NhY67aRNRz\"\n"
               + "    },\n"
               + "    \"fundingAmount\" : {\n"
               + "      \"currency\" : \"USD\",\n"
               + "      \"amount\" : 570549032\n"
               + "    },\n"
               + "    \"activeFrom\" : \"1990-06-14T00:55:15.940Z\",\n"
               + "    \"activeTo\" : \"2001-07-06T10:52:53.410Z\"\n"
               + "  }, {\n"
               + "    \"type\" : \"ConfirmedFunding\",\n"
               + "    \"source\" : \"https://www.example.org/sitmolestias\",\n"
               + "    \"id\" : \"https://www.example.org/estnisi\",\n"
               + "    \"identifier\" : \"lKcWsPWAe6IMh9dMl9\",\n"
               + "    \"labels\" : {\n"
               + "      \"it\" : \"WqLUE6PGwy4WGVHAmU\"\n"
               + "    },\n"
               + "    \"fundingAmount\" : {\n"
               + "      \"currency\" : \"EUR\",\n"
               + "      \"amount\" : 566650900\n"
               + "    },\n"
               + "    \"activeFrom\" : \"1993-09-20T17:20:39.495Z\",\n"
               + "    \"activeTo\" : \"2002-08-20T19:00:43.517Z\"\n"
               + "  } ],\n"
               + "  \"additionalIdentifiers\" : [ {\n"
               + "    \"type\" : \"AdditionalIdentifier\",\n"
               + "    \"source\" : \"fakesource\",\n"
               + "    \"value\" : \"1234\"\n"
               + "  } ],\n"
               + "  \"subjects\" : [ \"https://www.example.org/enimcorrupti\" ],\n"
               + "  \"associatedArtifacts\" : [ {\n"
               + "    \"type\" : \"PublishedFile\",\n"
               + "    \"identifier\" : \"cf1a09ed-0977-498a-ab02-6fc7393a2199\",\n"
               + "    \"name\" : \"djJ1LoC5AVpuhd6\",\n"
               + "    \"mimeType\" : \"gpexBsQtBWpI0\",\n"
               + "    \"size\" : 1009830760,\n"
               + "    \"license\" : {\n"
               + "      \"type\" : \"License\",\n"
               + "      \"identifier\" : \"NqZavHmBUkWJpt\",\n"
               + "      \"labels\" : {\n"
               + "        \"en\" : \"GkV5UAUdwfuCFfQ\"\n"
               + "      },\n"
               + "      \"link\" : \"https://www.example.com/29P6Nqc6FN6\"\n"
               + "    },\n"
               + "    \"administrativeAgreement\" : false,\n"
               + "    \"publisherAuthority\" : true,\n"
               + "    \"publishedDate\" : \"1978-03-16T19:39:53.900Z\",\n"
               + "    \"visibleForNonOwner\" : true\n"
               + "  }, {\n"
               + "    \"type\" : \"AssociatedLink\",\n"
               + "    \"id\" : \"https://www.example.com/xBLHmQNcu73pqUHHePi\",\n"
               + "    \"name\" : \"Z2cMOWx2HPr\",\n"
               + "    \"description\" : \"X6oVyB2AXNG8E2coj\"\n"
               + "  } ],\n"
               + "  \"rightsHolder\" : \"kJumxBb2pfFNfoD\",\n"
               + "  \"modelVersion\" : \"0.20.10\"\n"
               + "}";
    }
}
