plugins {
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    implementation project(':publication-rest')
    implementation(project(':publication-commons')) {
        exclude group: "software.amazon.ion", module: "ion-java"
    }
    implementation project(':publication-constants')
    implementation project(':publication-model')

    implementation nvaLibs.apigateway
    implementation nvaLibs.core
    implementation nvaLibs.auth
    implementation nvaLibs.clients
    implementation nvaLibs.json

    implementation nvaCatalog.aws.lambda.core
    implementation nvaCatalog.aws.sdk2.dynamo
    implementation nvaCatalog.jackson.databind
    implementation nvaCatalog.log4j.core
    implementation nvaCatalog.slf4j.api

    implementation(nvaCatalog.aws.sdk2.dynamodblocal) {
        exclude group: 'com.amazonaws', module: 'aws-java-sdk-dynamodb'
        exclude group: 'com.amazonaws', module: 'aws-java-sdk-core'
        exclude group: 'org.eclipse.jetty'
        exclude group: 'org.eclipse.jetty.ee10'
        exclude group: 'org.eclipse.jetty.ee10.websocket'
    }

    implementation libs.javalin
    implementation libs.swagger.core
}

application {
    mainClass = 'no.unit.nva.publication.adapter.AdapterApplication'
}
