name: Trigger DynamicPipelineMakerLambda

on:
  pull_request:
    types: [opened, closed]

jobs:
  dynamic-pipeline-maker-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DynamicPipelineMakerLambda
        id: invoke
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: eu-west-1
          FunctionName: ${{ secrets.AWS_CICD_FUNCTION_NAME }}
          LogType: Tail
          Payload: ${{ toJSON(github) }}
      - name: Store tail logs to file
        run: echo "${{ fromJSON(steps.invoke.outputs.response).LogResult }}" > invocation-logs.json
