name: Trigger DynamicPipelineMakerLambda

on:
  pull_request:
    types: [opened, closed]

jobs:
  dynamic-pipeline-maker-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DynamicPipelineMakerLambda
        uses: gagoar/invoke-aws-lambda@master
        env:
          EVENT: '"{ "github": { "repository": "{0}", "event_name": "{1}", "event": { "action": "{2}" }, "ref": "{3}" } }"'
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: eu-west-1
          FunctionName: ${{ secrets.AWS_CICD_FUNCTION_NAME }}
          Payload: ${{ format(env.EVENT, github.repository, github.event_name, github.event.action, github.ref) }}